apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-container
      image: 516503768003.dkr.ecr.us-east-1.amazonaws.com/ecr_assignment2:mysql-v0.1
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
      ports:
        - containerPort: 3306
  imagePullSecrets:
          - name: ecr-registry-secret
